name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]          # build every time you push to main
permissions:
  contents: write             # allow the deploy Action to push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + Material theme
        run: |
          pip install mkdocs-material

      - name: Build site
        run: |
          mkdocs build --strict --site-dir site

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
          cname: ''            # leave empty unless you have a custom domain
